mysite/account/urls.py
from django.conf.urls import url
from .import views

from django.conf import settings
from django.contrib.auth import views as auth_views #引入内置视图文件并重新命名为

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'),   #自定义的登陆
    url(r'^login/$', auth_views.login, name='user_login'),  #django内置登陆
    #url(r'^new-login/$', auth_views.login, {"template_name": 'account/login.html'}),    #传值 跳转至自定义登陆模板
    #url(r'^logout/$', auth_views.logout, name='user_logout')，    #django内置退出模板
    url(r'^logout/$', auth_views.logout, {"template_name": 'account/logout.html/'}, name='user_logout'),
    url(r'^register/$', views.register, name='user_register'),
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect': '/account/password-change-done'}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^my-information/$', views.myself, name='my_information'),
    url(r'^edit-my-information/$', views.myself_edit, name='edit_my_information'),
]

mysite/article/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name='article_column'),
]

mysite/blog/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'^(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    #url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^pwd_reset/', include('password_reset.urls', namespace='pwd_reset', app_name='pwd_set')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
]

mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now=True)

    def __str__(self):
        return self.column

mysite/article/forms.py
from django import forms
from .models import ArticleColumn

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

mysite/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import ArticleColumn
from .forms import ArticleColumnForm
from django.http import HttpResponse


# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:

            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")

mysite/templates/article/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<div class="container">
    {% include 'article/header.html' %}
    <div class="col-md-2">
    {% include 'article/leftslider.html' %}
    </div>
    <div class="col-md-10">
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}
</div>
</body>
</html>

mysite/templates/article/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.lakeface.xin"><img width="20px" src="{% static 'images/go.png' %}"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="tablist">
                <li><a href="{% url 'article:article_column' %}">文章管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                <li><a href="{% url 'blog:blog_title' %}">网站首页</a></li>
                <li><span>{{ user.username }}</span></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
            </ul>
        </div>
    </nav>
</div>

mysite/templates/article/leftslider.html
<div class="bg-info">
    <div class="text-center" style="margin-top: 5px;">
        <p><h4>文章管理</h4></p>
        <p><a href="{% url 'article:article_column'%}">栏目管理</a></p>
    </div>
</div>